prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: 
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
grafana:
  adminPassword: admin
  deploymentStrategy:
    type: Recreate
  persistence:
    enabled: true
    type: pvc
    storageClassName: gp2
    accessModes: 
      - ReadWriteOnce
    size: 4Gi
    finalizers:
    - kubernetes.io/pvc-protection